name: "Deploy Graphl Server to Google Cloud Run"

on:
  workflow_dispatch:
    inputs:
      env:
        description: "environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  PROJECT_ID: ${{ (github.event.inputs.env == 'prod') && (secrets.GCP_PROJECT_ID) || (secrets.DEV_GCP_PROJECT_ID) }}
  WIF_PROVIDER: ${{ (github.event.inputs.env == 'prod') && (secrets.WIF_PROVIDER) || (secrets.DEV_WIF_PROVIDER) }}
  SA_ACCOUNT: ${{ (github.event.inputs.env == 'prod') && (vars.SA_ACCOUNT) || (vars.DEV_SA_ACCOUNT) }}
  SERVICE_NAME: listen
  GCP_REGION: asia-northeast1
  APP: listen-graphql

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ env.WIF_PROVIDER }}"
          service_account: "${{ env.SA_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{env.PROJECT_ID}}

      - name: Docker Auth
        run: gcloud auth configure-docker ${{env.GCP_REGION}}-docker.pkg.dev

      - name: Build and Push container
        run: |-
          docker build -f ./packages/graphql-server/Dockerfile -t "${{env.GCP_REGION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" .
          docker push "${{env.GCP_REGION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"

      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: "${{env.GCP_REGION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
          service: "${{ env.SERVICE_NAME }}"
          region: "${{env.GCP_REGION}}"
